language: python
sudo: false

#python:
#  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"

env:
  global:
    - LD_LIBRARY_PATH=./libsecp256k1_ext/.libs
    - DYLD_FALLBACK_LIBRARY_PATH=./libsecp256k1_ext/.libs
    - LIB_DIR=./libsecp256k1_ext/.libs
    - INCLUDE_DIR=./libsecp256k1_ext/include
    - PYPI_USERNAME=test_secp_deploy
    - secure: "BA018G6688huuq24WfjQ9qBuf38YvXMcWm77zi6tca11gzrxq+5N4CHw0bWDLuOKBvLpXzTATn4PizAgHy2kwoO5q77psNf0btV8Y4t8hvsAsiENt7QyBnUD7gmx1bJtXhd9xjCA3dvBVTfhl64Kb7D8ZavZwHx/Vlj7Qv1CJrHdt3u0t7qjounEjHSOkF7FIwFxeYjxhAMdFnaNcPinvNcqx0TdavmFpZCuQ4xAbq0aiL3RV04GnXZzRIzyARciXr8uSPXP3iTba2LFNSdnoCw7hz06AgvVU0juR4nS/zeX5Zfy6UmGpf49SdoziFhZ06Wktwd6GoyPBYL5Z53vOxnSqNxpwKNeqa1H57Vlt3I4Gk5jjnFZtZxFKVNFwQObOFzhJ4zUJ9RfSgf3mXKaUvSPrEHnrc9CP0D6pQSoDPom8BGZFJMgG4rVISBOKlB+JXh4IUTghZfxKJxO6kSLaRG6Z+vEu10MhQogrc/8lbwtEUsEaQqQuZIupLfUIhxIHCeSRf1Qz/khSZtzn9mmBOsVYkYF4OzQO1Y1GwlUSgfvluI+SgQyo6DhZWprIO6xOH0rmQU6wdG6eaueoFxnkl6LFt5ayD7GXGNBTNc2tKaWd7cYHHPYtcmb7QG2TfWSCwy8VQGYkce5wrbR9IuZR2ONKB4LMRtrFVo2i/+GKuQ="
#  matrix:
#    - BUNDLED=0
#    - BUNDLED=1
#    - BUNDLED=1 SECP_BUNDLED_EXPERIMENTAL=1

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/python-dl

# Sigh... Until Travis issue #2312 is fixed Travis' osx image doesn't support
# Python so we need to manually specify this matrix...
matrix:
  include:
    - os: osx
      language: generic
      osx_image: xcode7.1
      python: 2.7
      env:
        - TRAVIS_PYTHON_VERSION=2.7
        - BUNDLED=0
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 2.7
#      env:
#        - TRAVIS_PYTHON_VERSION=2.7
#        - BUNDLED=1
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 2.7
#      env:
#        - TRAVIS_PYTHON_VERSION=2.7
#        - BUNDLED=1
#        - SECP_BUNDLED_EXPERIMENTAL=1
#
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 3.3
#      env:
#        - TRAVIS_PYTHON_VERSION=3.3
#        - BUNDLED=0
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 3.3
#      env:
#        - TRAVIS_PYTHON_VERSION=3.3
#        - BUNDLED=1
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 3.3
#      env:
#        - TRAVIS_PYTHON_VERSION=3.3
#        - BUNDLED=1
#        - SECP_BUNDLED_EXPERIMENTAL=1
#
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 3.4
#      env:
#        - TRAVIS_PYTHON_VERSION=3.4
#        - BUNDLED=0
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 3.4
#      env:
#        - TRAVIS_PYTHON_VERSION=3.4
#        - BUNDLED=1
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 3.4
#      env:
#        - TRAVIS_PYTHON_VERSION=3.4
#        - BUNDLED=1
#        - SECP_BUNDLED_EXPERIMENTAL=1
#
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 3.5
#      env:
#        - TRAVIS_PYTHON_VERSION=3.5
#        - BUNDLED=0
#    - os: osx
#      language: generic
#      osx_image: xcode7.1
#      python: 3.5
#      env:
#        - TRAVIS_PYTHON_VERSION=3.5
#        - BUNDLED=1
    - os: osx
      language: generic
      osx_image: xcode7.1
      python: 3.5
      env:
        - TRAVIS_PYTHON_VERSION=3.5
        - BUNDLED=1
        - SECP_BUNDLED_EXPERIMENTAL=1

addons:
  apt:
    packages:
      - git
      - libtool
      - autoconf
      - automake
      - pkg-config
      - libffi-dev
      - libgmp-dev

before_install:
  - source .travis/install.sh
  - python --version
  - python -m pip install -U setuptools cffi pytest coverage coveralls

install:
  - env
  - python --version
  #- python setup.py install

# This is a bit of a hack:
# We want to ensure that we test the installed version, not the local source.
# For that reason we rename the local source directory before running the
# tests.
# Unfortunately this compilcates using coverage. We use '--parallel' and
# 'combine' together with the `paths` setting in '.coveragerc' to massage it
# into producing correct paths. For that to work we need to re-rename the
# source back to it's correct name.
script:
   - env
   - python --version
#  - mv secp256k1 _secp256k1
#  - coverage run --parallel --include="*/site-packages/*.egg/secp256k1/*" -m py.test
#  - mv _secp256k1 secp256k1
#  - coverage combine

#after_success:
#  - coveralls

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: autodeploy
#    tags: true
